sensorConfig: [
   {magnitude: CO,            updateTime: 10,  mongoNames: [Env_cO] },
   {magnitude: particleCount, updateTime: 10,  mongoNames: [Env_particleCount] },
   {magnitude: VOC,           updateTime: 10,  mongoNames: [Env_vOCResistance] },
   {magnitude: temp,          updateTime: 30,  mongoNames: [Env_temp,Kitchen_Multi_Temp,Entry_Multi_Temp,Lounge_Multi_Temp,Workshop_Multi_Temp,Office1_Multi_Temp,Office2_Multi_Temp] },
   {magnitude: humidity,      updateTime: 30,  mongoNames: [Env_humidity,Office1_Multi_Humid] },
   {magnitude: light,         updateTime: 300, mongoNames: [Env_light,Kitchen_Multi_Lux,Entry_Multi_Lux,Lounge_Multi_Lux,Workshop_Multi_Lux,Office1_Multi_Lux,Office2_Multi_Lux] } ]
