to_pose_array:
    detectors:                                  # Add detectors under this namespace
        leg_detector:                           # Name of detector (used internally to identify them. Has to be unique.
            topic: "/people_tracker_measurements"  # The topic on which the geometry_msgs/PoseArray is published
            point_name: "pos"                   # The name of the point containing the coordinates in question

        upper_body_detector:                           # Name of detector (used internally to identify them. Has to be unique.
            topic: "/upper_body_detector/bounding_box_centres"  # The topic on which the geometry_msgs/PoseArray is published
            point_name: "poses"                   # The name of the point containing the coordinates in question
